server:
  http_listen_port: 18980
  grpc_listen_port: 0

positions:
  filename: /grafana/positions.yml # This location needs to be writeable by Promtail.

client:
  url: http://loki:18310/loki/api/v1/push

scrape_configs:
 - job_name: system
   pipeline_stages:
   - docker:
   - regex:
      # version source: https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string with some modification
      expression: ".*[^\\d\\.\\/](?P<version>(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?)[^\\.\\d:]"
   - regex:
      source: filename
      # network, service
      expression: "^\\/var\\/tari\\/(?P<network>.+?)\\/log\\/(?P<service>.+?)(.\\d)?.log\\/$"
   - regex:
      # time, source, level, content
      expression: "^(?P<time>\\d{4}-\\d{2}-\\d{2}\\s\\d{2}:\\d{2}:\\d{2}\\.\\d{9})\\s\\[(?P<source>(\\w|:)+)\\]\\s(?P<level>\\w+)\\s+(?P<content>.+)$"
   - labels:
      service:
      source:
      level:
      version:
      network:
   - timestamp:
      source: time
      format: RFC3339Nano
   - output:
      source: content
   static_configs:
   - labels:
      __path__: /var/tari/**/log/*.log  # The path matching uses a third party library: https://github.com/bmatcuk/doublestar
