export default {
  settings: {
    title: 'Advanced Settings',
    subtitle: 'Danger Zone',
    label: 'Reset changes',
    warning: '⚠️ This action cannot be undone',
    description:
      'Clean all settings and start from scratch (requires restarting)',
    resetButton: 'Reset',
    keepEditing: 'Keep editing',
    resetAndExit: 'Reset & Exit',
    reset: 'Reset',
    export: "Export",
    exportDescription: "Export all logs generated by the Tari Launchpad to the Downloads directory.",
  },
};
